# The art of mixing
- [The art of mixing David Gibson](https://www.youtube.com/watch?v=TEjOdqZFvhY)
Analyze it:
- for example at 28:00 he says with eq, stereo, reverb and volume (something else) we can design mixes based on of they are sparse or busy.
- Or how a lot of modern stuff has high volume kick but big band the kick is low since the instruments are way more important there actually: 35:12. SO yeah in big band and jazz (at least true jazz and big band) the bass is probably more important than kick so no sidechain and you wanna equalize the kick more around the bass then opposite as you usually do.
- Good thing on compression at 50:00. Like u wanna stabilize, generally the more stuff the more u need to compress to stablize stuff, and second if u need louder and fatter. Like if you need main lead sound and needs to sound clear of course eq around it but also turn up and compress. I should really put this somewhere. Like if u have brackground elements, u dont wanna lose ull compress 'em and since background you can compress the hell out of them. Good starting point comp is 4:1 and -6db threshold.
- At 1:42:00 common sound levels for certain sounds. Look at the shock, in modern music this could be like a fill where a single vocal thus really loud like just like stuff that is short (so not the hwole time) but kind of does awaken us a little, like maybe some sudden orchestral hit (though of course always balance).
- From 1:50:00 goes into levels of common elements per instrument and genre (just suggestions of course)
- Panning and stereo traditions 2:13:00. So yeah look at the toms, you often hear that transition with the toms with this panning from left to right and then play tom 1 tom 2 going to fl from left to right or left right left right.
- At 2:21:00 starts explaining how fx can make a dull perfectly fine composed and arranged mix sound fuller and more like a wall of sound. Usuaully the busier the mix the sublte (or more automated ur fx or more short) like do the big delays only on quiet(er) parts of the chorus sounds, big reverbs same etc.

Also look at the Arcade guy guide (or another) for basic formulaic levels to kind of get your sound right for electronic music. Again this is more genre and styl dependent though. And use Wave Candy for real metereing (kind of like YouLean) instead of the mix meter as it doesn't reflect true loudness, like you might think a lead is kind of quiet on meter but see on Wave Candy and it's actually fine.
